#!/usr/bin/env bash
#
# Shell script template.
#
# Author: Michal Svorc <dev@michalsvorc.com>
# License: MIT license (https://opensource.org/licenses/MIT)
# Guidelines: https://google.github.io/styleguide/shell

#===============================================================================
# Shell script execution options
#===============================================================================

set -o errexit  # Exit if any command exits with a nonzero (error) status.
set -o nounset  # Disallow expansion of unset variables.
set -o pipefail # Use last non-zero exit code in a pipeline.
set -o errtrace # Ensure the error trap handler is properly inherited.

# Enable shell script debugging mode when the DEBUG environment variable is set.

#===============================================================================
# Variables
#===============================================================================

dir_profile="${1-$HOME/.local/profile}"
readonly dir_profile
readonly repository_url='https://github.com/michalsvorc/profile'

#===============================================================================
# Execution
#===============================================================================

git clone \
  --recurse-submodules \
  --depth 1 \
  --branch 'main' \
  "$repository_url" "$dir_profile" &&
  bash "${dir_profile}/scripts/init.sh"
